name: Solutions

on:
  push:
  pull_request:
 
concurrency:
  group: ${{ github.workflow }}=${{ github.ref == 'refs/head/main' && github.run_number || github.ref }}
  cancel-in-progress: true

jobs:
  cmake_and_ctest:
    name: CMake & CTest, ${{ matrix.variant.os }}
    runs-on: ${{ matrix.variant.os }}
    defaults:
      run:
        shell: bash -l {0}
    strategy:
      fail-fast: false
      matrix:
        variant:
          - {os: ubuntu-latest}
          - {os: macos-latest}
          - {os: windows-latest}
        cmake-type: ['Release', 'Debug']

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: CCache
        uses: hendrikmuhs/ccache-action@v1.2.2
        with:
          key: ${{ matrix.variant.os }}

      - name: Configure
        run: cmake -S . -B build -D CMAKE_BUILD_TYPE=${{ matrix.cmake-type }}
      
      - name: Count cores
        uses: SimenB/github-actions-cpu-cores@v1
        id: cpu-cores

      - name: Build
        run: cmake --build build --config ${{ matrix.cmake-type }} --parallel ${{ steps.cpu-cores.outputs.count }}

      - name: Test
        working-directory: build
        run: ctest -C ${{ matrix.cmake-type }} --output-on-failure --parallel ${{ steps.cpu-cores.outputs.count }}
